rdiscount: true
highlighter: pygments
#lsi: true
paginate: 10
permalink: "/:year/:month/:title"
url: "http://gusiev.com"
content_delimeter: "<!--more-->"
gems: [jekyll-paginate]
exclude:
  - slides
  - build
