require "open-uri"
require "#{__dir__}/app"
# load "#{__dir__}/../../Rakefile"

namespace :slides do
  task :build do
    html = MyApp.new.call(
    'REQUEST_METHOD' => 'GET',
    'PATH_INFO' => '/',
    'rack.input' => StringIO.new
  )[2].join('')
    File.write("#{__dir__}/index.html", html)
  end
  task :deploy => ['slides:build'] do
    puts `bundle exec --gemfile=../../Gemfile "rake --rakefile ../../Rakefile deploy"`
  end
end
